# Generated by Django 5.1.7 on 2025-04-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='subject_images/')),
                ('board', models.CharField(choices=[('CBSE', 'CBSE'), ('STATE', 'STATE')], max_length=20)),
                ('class_level', models.IntegerField()),
            ],
        ),
    ]
