# Generated by Django 5.1.7 on 2025-04-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0003_remove_subject_board_remove_subject_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubmission',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='stream',
        ),
        migrations.AddField(
            model_name='subject',
            name='board',
            field=models.CharField(choices=[('CBSE', 'CBSE'), ('STATE', 'STATE')], default='CBSE', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subject_images/'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='StudentSubmission',
        ),
    ]
