# Generated by Django 5.1.7 on 2025-04-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0006_question_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='subject_scores',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
