# Generated by Django 5.1.7 on 2025-04-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0007_studentsubmission_subject_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
    ]
