# Generated by Django 5.1.7 on 2025-04-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0009_alter_question_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4')], default=1),
        ),
    ]
