# Generated by Django 5.1.7 on 2025-04-29 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr_app', '0010_alter_question_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSavedQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omr_app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omr_app.subject')),
            ],
            options={
                'verbose_name': 'Student Saved Question',
                'verbose_name_plural': 'Student Saved Questions',
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
